- core/feature/erratic_driving.py
- core/signalprocessing/ppg.py
Hi Dr. Ali,
These are files designated to me.
Thanks
> added the files

- core/feature/phone_features/phone.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/11)
> Phone features with data storing in cerebralcortex

- core/markers/gps/gps_clustering.py
- core/markers/gps/metadata/gps_data_clustering_episode_generation.json
- requirements.txt
Dear Dr. Ali,
Please review the pull request and let me know if I need to make further changes.
Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/10)
> Gps Data clustering and episode generation

- core/feature/phone_features/metadata/average_inter_phone_call_sms_time_daily.json
- core/feature/phone_features/metadata/average_inter_phone_call_sms_time_four_hourly.json
- core/feature/phone_features/metadata/average_inter_phone_call_sms_time_hourly.json
- core/feature/phone_features/metadata/average_inter_phone_call_time_daily.json
- core/feature/phone_features/metadata/average_inter_phone_call_time_four_hourly.json
- core/feature/phone_features/metadata/average_inter_phone_call_time_hourly.json
- core/feature/phone_features/metadata/average_inter_sms_time_daily.json
- core/feature/phone_features/metadata/average_inter_sms_time_four_hourly.json
- core/feature/phone_features/metadata/average_inter_sms_time_hourly.json
- core/feature/phone_features/metadata/variance_inter_phone_call_sms_time_daily.json
- core/feature/phone_features/metadata/variance_inter_phone_call_sms_time_four_hourly.json
- core/feature/phone_features/metadata/variance_inter_phone_call_sms_time_hourly.json
fixed stream names corresponding to marker document containing the marker name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/13)
> CC-457 Fixed stream names in the metadata files.

- core/feature/gps/gps.py
- core/feature/gps/gps_groundtruth.py
- core/feature/gps/metadata/gps_episodes_and_semantic_location.json
Dear Anand,
Please review the code and let me know if I need to make any changes.
Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/16)
> GPS clustering and episode generation

- .travis.yml
- core/computefeature.py
- core/driver.py
- core/feature/phone_features/phone_features.py
- core/feature/phone_features/test_phone_features.py
- core/utils/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/17)
> CC-448 Prototype of a unittest framework

- core/feature/activity/activity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/28)
> Fixed bug ''list' object has no attribute 'sample''

- core/feature/activity_features/activity_features.py
- core/feature/activity_features/utils.py
- core/resources/metadata/high_activity_time_hourly.json
- core/resources/metadata/lying_time_hourly.json
- core/resources/metadata/moderate_activity_time_hourly.json
- core/resources/metadata/sitting_time_hourly.json
- core/resources/metadata/standing_time_hourly.json
- core/resources/metadata/walking_time_hourly.json
Compute activity and poster features (hourly + daily) from activity&posture output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/36)
> Compute activity and poster features (hourly + daily) from activity&posture output

- core/feature/beacon/beacon.py
- core/resources/metadata/home_beacon_context.json
- core/resources/metadata/work_beacon_context.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/42)
> changed beacon.py and metadata

- core/feature/office_time/arrival_time.py
- core/feature/office_time/arrival_time_from_beacon.py
- core/feature/office_time/expected_arrival_time.py
- core/feature/office_time/expected_arrival_time_from_beacon.py
- core/feature/office_time/expected_staying_time.py
- core/feature/office_time/expected_staying_time_from_beacon.py
- core/feature/office_time/office_time.py
- core/feature/office_time/staying_time.py
- core/feature/office_time/staying_time_from_beacon.py
- core/feature/office_time/work_days_from_beacon.py
- core/resources/metadata/working_days_from_beacon.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/44)
> Modified Office Time

- core/feature/beacon/beacon.py
- core/resources/metadata/home_beacon_context.json
- core/resources/metadata/work_beacon_context.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/52)
> Beacon's metadata and return value changes

- core/feature/activity/activity.py
- core/feature/activity_features/activity_features.py
- core/feature/activity_features/utils.py
- core/resources/metadata/activity_type_accelonly_10seconds_window.json
- core/resources/metadata/high_activity_time_daily.json
- core/resources/metadata/high_activity_time_daily_accel_only.json
- core/resources/metadata/high_activity_time_hourly.json
- core/resources/metadata/high_activity_time_hourly_accel_only.json
- core/resources/metadata/high_activity_time_imputed_day_of_week_daily.json
- core/resources/metadata/high_activity_time_imputed_day_of_week_daily_accel_only.json
- core/resources/metadata/high_activity_time_imputed_time_of_day_daily.json
- core/resources/metadata/high_activity_time_imputed_time_of_day_daily_accel_only.json
- core/resources/metadata/moderate_activity_time_daily.json
- core/resources/metadata/moderate_activity_time_daily_accel_only.json
- core/resources/metadata/moderate_activity_time_hourly_accel_only.json
- core/resources/metadata/moderate_activity_time_imputed_day_of_week_daily.json
- core/resources/metadata/moderate_activity_time_imputed_day_of_week_daily_accel_only.json
- core/resources/metadata/moderate_activity_time_imputed_time_of_day_daily.json
- core/resources/metadata/moderate_activity_time_imputed_time_of_day_daily_accel_only.json
- core/resources/metadata/posture_10seconds_window.json
- core/resources/metadata/posture_accelonly_10seconds_window.json
- core/resources/metadata/walking_time_daily.json
- core/resources/metadata/walking_time_daily_accel_only.json
- core/resources/metadata/walking_time_hourly.json
- core/resources/metadata/walking_time_hourly_accel_only.json
- core/resources/metadata/walking_time_imputed_day_of_week_daily.json
- core/resources/metadata/walking_time_imputed_day_of_week_daily_accel_only.json
- core/resources/metadata/walking_time_imputed_time_of_day_daily.json
- core/resources/metadata/walking_time_imputed_time_of_day_daily_accel_only.json
-Imputed with time of day
-Imputed with time of day of week
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/55)
> Added activity type daily feature

- core/feature/beacon/beacon.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/59)
> Documentation for beacon.py

- core/feature/data_yield/__init__.py
- core/feature/data_yield/data_yield.py
- core/feature/heart_rate/__init__.py
- core/feature/heart_rate/heart_rate.py
- core/feature/motionsenseHRVdecode/__init__.py
- core/feature/motionsenseHRVdecode/motionsenseHRVdecode.py
- core/feature/respiration_cycle_statistics/__init__.py
- core/feature/respiration_cycle_statistics/respiration_cycle_statistics.py
- core/feature/rr_interval/__init__.py
- core/feature/rr_interval/rr_interval.py
- core/feature/stress_from_respiration/__init__.py
- core/feature/stress_from_respiration/stress_from_respiration.py
- core/feature/stress_from_wrist/__init__.py
- core/feature/stress_from_wrist/stress_from_wrist.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/60)
> Necessary Comments and Docstrings added

- core/feature/rr_interval/rr_interval.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/71)
> added qualtrics check

- core/feature/activity_features/activity_features.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/87)
> ARGENT: Fixed filepath error... please merge and rerun

- core/feature/puffmarker/puffmarker.py
did not check for zero stream size
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/96)
> fixed new bug

- core/feature/rr_interval/rr_interval.py
- core/feature/rr_interval/utils/util_helper_functions.py
- core/resources/metadata/rr_interval_data_presence.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/92)
> added rr_interval changes to run with resume capability

- core/feature/puffmarker/puffmarker.py
- core/resources/metadata/hand_to_mouth_leftwrist.json
- core/resources/metadata/hand_to_mouth_rightwrist.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/105)
> Added hand-to-mouth gesture as new stream for both wrist

- core/feature/rr_interval/utils/util_helper_functions.py
- core/resources/metadata/rr_interval.json
- core/resources/metadata/rr_interval_data_presence.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/104)
> changed rr interval stream name

- core/feature/puffmarker/puffmarker.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/md2korg/cerebralcortex-dataanalysis/108)
> Fixed bug related to hand-to-mouth gestures

- core/feature/PPGHourYield/PPGHourYield.py
Hi Ananda,
This is the pull request.
Thanks,
Azim
> PPGHourYield Fixed 

- core/feature/DecodeHRV/DecodeHRV.py
Hi Dr. Hnat,
Will you please run 'DecodeHRV' on all participants of mperf field study? We need to finish this computation within a week.
I included day-wise checking in there. So the days where we have data, we won't be doing anything on it.
Thanks,
Azim
> Need to run DecodeHRV on all participants of mperf

- core/feature/DecodeHRV/DecodeHRV.py
- core/feature/PPGHourYield/PPGHourYield.py
- core/feature/PresenceDecodeHRV/PresenceDecodeHRV.py
- core/feature/PresenceDecodeHRV/__init__.py
- core/resources/metadata/data_quality_motion_left.json
- core/resources/metadata/data_quality_motion_right.json
- core/resources/metadata/data_yield_left.json
- core/resources/metadata/data_yield_right.json
- core/resources/metadata/decoded_hrv_presence.json
Hi Ananda,
Please run 'PresenceDecodeHRV' for all participants in 'mperf'. If possible please run the 'DecodeHRV' code with 30 participants at a time in a loop with more cores please. We need to finish the computation.
Thanks,
Azim
> Please run 'DataQualityPPG'.

- core/feature/PPGHourYield/PPGHourYield.py
- core/resources/metadata/data_yield_left.json
- core/resources/metadata/data_yield_right.json
Please run PPGHourYield for all participants in batches.
This should be quite faster than the previous version.
> finalized PPGHourYield
